Add flatpak build manifest and necessary extra data
shadps4-emu/shadPS4-flatpak pull request #1
Opened 2024-11-08 00:32 UTC by fpiesche

There's some TODOs here - feedback on these would be good!

2024-11-08 08:15 UTC, ngoquang2708 commented on net.shadps4.shadps4.yml
> +  # TODO: libfmt is included as a submodule in externals - do we need to build it separately?
The KDE Runtime 6.8 is currently missing ```libfmt```. There is a merged PR to add ```libfmt``` to the FreeDesktop Runtime, which KDE Runtime based on. I don't know how long until the KDE Runtime get updated.
At the mean time, we can use something similar to this
```
    post-install:
      # FIXME Temporary workaround until libfmt is added to the runtime
      - cp /lib/*-linux-gnu/libfmt* /app/lib/
```

and then we can remove ```libfmt``` from this manifest.

2024-11-08 08:24 UTC, ngoquang2708 commented on net.shadps4.shadps4.yml
> +  - name: evdev
I can confirm that this is not needed. AppImages don't include this as well.

2024-11-08 08:29 UTC, ngoquang2708 commented
Missing this https://github.com/shadps4-emu/shadPS4/pull/1474#issuecomment-2453822651.

2024-11-08 08:30 UTC, ngoquang2708 commented on net.shadps4.shadps4.yml
> +  # Discord rich presence?
https://github.com/shadps4-emu/shadPS4/pull/1474#issuecomment-2454254735

2024-11-08 08:41 UTC, fpiesche commented on net.shadps4.shadps4.yml
> +  # TODO: libfmt is included as a submodule in externals - do we need to build it separately?
Ah, is it in the submodules just for the headers? I was wondering if it gets built alongside shadps4 if it's not on the system itself since it's included there.

2024-11-08 08:46 UTC, ngoquang2708 commented on net.shadps4.shadps4.yml
> +  # TODO: libfmt is included as a submodule in externals - do we need to build it separately?
The one in submodules is just a fallback for when the host don't have it installed.

2024-11-08 08:53 UTC, fpiesche commented
> How do we handle release/nightly update channels?

Flathub itself is mostly intended for stable releases, and this manifest is geared around that (cf. the x-checker-data segments looking for tagged releases in the shadps4 git repo).

Flathub does have a beta channel that could be used for dev builds; the way this is handled is by adding a `beta` branch to the `flathub/[app id]` repo that's created once the project is submitted; the manifest in that channel will be built and published to the public Flathub beta repository.

2024-11-08 09:03 UTC, ngoquang2708 commented on net.shadps4.shadps4.yml
> +app-id: net.shadps4.shadps4
I think this should change to this.
```suggestion
app-id: net.shadps4.shadPS4
```
That the way I see other apps used. Applied for other files as well.

2024-11-08 09:05 UTC, ngoquang2708 commented
> published to the public Flathub beta repository.

So if user want to use the beta channel they have to add the Flathub beta repo manually?

2024-11-08 09:11 UTC, ngoquang2708 commented on .gitignore
> +.flatpak-builder
These would be useful if if you want to build locally for testing purpose.
```suggestion
.flatpak-builder
builddir
repo
*.flatpak
```

2024-11-08 09:13 UTC, fpiesche commented
> > published to the public Flathub beta repository.
> 
> So if user want to use the beta channel they have to add the Flathub beta repo manually?

Yup, and install from the beta repo specifically either using the relevant control in their graphical package manager, or via `flatpak install flathub-beta net.shadps4.shadps4`.

2024-11-08 09:54 UTC, ngoquang2708 commented on net.shadps4.shadps4.metainfo.xml
> +  <icon type="remote" width="256" height="256" translate="no">https://cdn.jsdelivr.net/gh/shadps4-emu/shadps4@main/src/images/net.shadps4.shadps4.svg</icon>
To avoid any frictions that block this PR from getting merged, I think you should update external links to point back to GH or preferably to official website. Then when everything is sorted out. You can make another PR to update for these links.

2024-11-08 10:59 UTC, fpiesche commented on net.shadps4.shadps4.metainfo.xml
> +  <icon type="remote" width="256" height="256" translate="no">https://cdn.jsdelivr.net/gh/shadps4-emu/shadps4@main/src/images/net.shadps4.shadps4.svg</icon>
The jsdelivr links are just CDN mirrors for Github; jsdelivr is a free CDN for open-source projects backed by a number of the major commercial orgs in the CDN space - so any changes to these files in the github repository will be automatically reflected in the jsdelivr CDN cache.

2024-11-08 14:36 UTC, jardon commented on net.shadps4.shadps4.yml
> +        tag: v.0.4.0
how does this work with the releases xml?

2024-11-08 14:47 UTC, fpiesche commented on net.shadps4.shadps4.yml
> +        tag: v.0.4.0
It does not - the releases.xml is a manually maintained file and used mostly for information. For example, Flathub uses it to generate the "what's new in [version]" segment on its web listings for apps.

I'm working on, but haven't finished, a GitHub Action that can be run when a new GitHub release is created to plug the information from the GH release into the .releases.xml (or the metainfo.xml if required) and update the release tag to a new commit with the updated file. Once I've finished and tested this I'll be happy to PR a workflow to automatically maintain the releases.xml file :)

2024-11-08 19:04 UTC, fpiesche commented on net.shadps4.shadps4.yml
> +app-id: net.shadps4.shadps4
I would happily do this and there's no hard rules for this; however the FreeDesktop specification "strongly encourages" using only lowercase letters. One reason for this is that some uses of the ID are case sensitive; eg. the `flatpak` command (so eg. `flatpak install org.wesnoth.wesnoth` will not work because the package is named `org.wesnoth.Wesnoth`). With that in mind, would you still prefer the ID to match the normal `shadPS4` stylisation?

2024-11-09 03:08 UTC, ngoquang2708 commented on net.shadps4.shadps4.yml
> +app-id: net.shadps4.shadps4
As pointed out by the [Flatpak documentation#Requirements & Conventions](https://docs.flatpak.org/en/latest/conventions.html):
>As will be seen below and in future sections, this ID is expected to be used in a number of places. Developers must follow the standard [D-Bus naming conventions for bus names](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names) when creating their own IDs. This format is already recommended by the [Desktop File specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/file-naming.html) and also the [Appstream specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent).

From [D-Bus naming conventions for bus names](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names) :
>Interface names should start with the reversed DNS domain name of the author of the interface (in lower-case), like interface names in Java. It is conventional for the rest of the interface name to consist of words run together, with initial capital letters on all words ("CamelCase").

From [Desktop Entry Specification#file_naming](https://specifications.freedesktop.org/desktop-entry-spec/latest/file-naming.html):
>The name of the desktop entry should follow the "reverse DNS" convention: it should start with a reversed DNS domain name controlled by the author of the application, in lower case. The domain name should be followed by the name of the application, which is conventionally written with words run together and initial capital letters (CamelCase). For example, if the owner of example.org writes "Foo Viewer", they might choose the name org.example.FooViewer, resulting in a file named org.example.FooViewer.desktop. 

There is a section in the  [Flatpak documentation#Requirements & Conventions](https://docs.flatpak.org/en/latest/conventions.html) mentioned that:
>The domain portion of the ID must be in lowercase, and while not required, the application portion is recommended to be in lowercase as well. Therefore, you should use org.example.app.

But in practice, usually, app names use ```CamelCase```:
![Screenshot_20241109_100439](https://github.com/user-attachments/assets/03d97fd7-9114-4e12-ac33-bb5cb9720d3d)

In conclusion, using ```net.shadps4.shadPS4``` as ```app-id``` and naming files is the best choice.

2024-11-09 19:23 UTC, fpiesche commented on net.shadps4.shadps4.yml
> +app-id: net.shadps4.shadps4
Done!

2024-11-09 23:40 UTC, fpiesche commented
The 6.8 KDE runtime was rebuilt on Friday so should now have libfmt:

- [`org.freedesktop.Platform` v24.08.6 was built on Thursday, including the libfmt change](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases/freedesktop-sdk-24.08.6)
- `org.kde.Platform` was rebuilt on Friday, likely as a downstream build from the freedesktop 24.08.6 release:

```
KDE Application Platform - Shared libraries used by KDE applications

          ID: org.kde.Platform
         Ref: runtime/org.kde.Platform/x86_64/6.8
        Arch: x86_64
      Branch: 6.8
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 1.0 GB

      Commit: a8f6c0c5ae504721f64ef55689e0ffb603b2c65a161edf2d59b7fa6433be8687
      Parent: 247722ce3a44978223909cc2f448ccca48efed9c8e73b56d98e6b12b9022e7ee
     Subject: build of org.kde.Sdk, Fri Nov  8 02:05:06 UTC 2024 (d09f5c1159e9d3c387ed5ebc9591dcb612ae5ac9)
        Date: 2024-11-08 10:37:05 +0000
```

2024-11-14 15:54 UTC, jardon requested changes

2024-11-14 15:54 UTC, jardon commented on net.shadps4.shadPS4.yml
> +# TODO: vvvvv These can go away once shadPS4 PRs 1494 and 1495 are merged vvvvv
this needs to be updated.  im assuming the icon can be removed from this PR as well?

2024-11-14 16:13 UTC, ngoquang2708 commented
A bit nitpick but manifest file extension should be in full form ```yaml```.

2024-11-20 06:52 UTC, ngoquang2708 commented on net.shadps4.shadPS4.yml
> -        path: net.shadps4.shadPS4.releases.xml
Since PRs 1494 and 1495 are merged, do we need these files anymore?

2024-11-20 06:57 UTC, ngoquang2708 commented
Do we need these files here since we already had them in main repo?
```
net.shadps4.shadPS4.metainfo.xml
net.shadps4.shadPS4.releases.xml
net.shadps4.shadPS4_metadata.pot
```

2024-11-21 19:39 UTC, fpiesche commented on net.shadps4.shadPS4.yml
> +# TODO: vvvvv These can go away once shadPS4 PRs 1494 and 1495 are merged vvvvv
Sorted that - added a source for the icon from the main repo :)

2024-11-21 19:40 UTC, fpiesche commented on net.shadps4.shadPS4.yml
> +        tag: v.0.4.0
The main/"stable" branch of Flathub applications should generally be tagged releases where available; my best guess is that rpcs3 was added before that guideline was put in place. I'll create a separate PR for a beta branch using `main`.

2024-11-29 12:50 UTC, ngoquang2708 approved these changes

2024-12-06 18:59 UTC, merged